spring.application.name=auth-service

server.port = 4005
spring.datasource.url=jdbc:postgresql://localhost:5001/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
